#!/usr/bin/env python3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _auth import get_token


def main():
    token, err = get_token()
    if err:
        print(err, file=sys.stderr)
        sys.exit(1)
    print(token)


if __name__ == "__main__":
    main()
